import React, { Component } from 'react';
import {
    View,
    Text,
    TouchableHighlight,
    StyleSheet,
    Alert,
    ScrollView
} from 'react-native';



class PrivacyPolicy extends Component {
    constructor(props) {
        super(props);
    }

    go_back = () => {
        this.props.navigation.navigate('LoginScreen');
    }


    render() {

        const { navigate } = this.props.navigation;

        return (

            <View style={{ flex: 1, justifyContent: "center", alignItems: "center", padding: 15, backgroundColor: "#00b3c0" }} >
                <ScrollView>
                    <View style={{ padding: 15, marginTop: 10 }} >

                        <View style= {{alignItems: 'center'}}>

                            <TouchableHighlight
                                style={styles.buttonStyle}
                                onPress={() => {
                                    this.go_back();
                                }}
                            >

                                    <Text style={{ fontWeight: 'bold'}}> Back </Text>

                            </TouchableHighlight>
                            
                        </View>

                    </View>

                    <View style={{ paddingTop: 10,paddingBottom: 10, flexDirection: 'row' }}>

                        <Text style={{ fontWeight: 'bold' }}>
                            {"\t"}Privacy Policy{"\n"}  
                            {"\t"}=============={"\n"}{"\n"}
                            
                            Effective date: November 18, 2019{"\n"}

                            Nutrition Go ("us", "we", or "our") operates the Nutrition Go mobile
                            application (hereinafter referred to as the "Service"). {"\n"}{"\n"}

                            This page informs you of our policies regarding the collection, use, and
                            disclosure of personal data when you use our Service and the choices you have
                            associated with that data. {"\n"}{"\n"}

                            We use your data to provide and improve the Service. By using the Service, you
                            agree to the collection and use of information in accordance with this policy.
                            Unless otherwise defined in this Privacy Policy, the terms used in this
                            Privacy Policy have the same meanings as in our Terms and Conditions. {"\n"}{"\n"}

                            
                            {"\t"}Definitions{"\n"}  
                            {"\t"}-----------{"\n"}

                            {"\t"}* Service{"\n"}

                            {"\t"}Service is the Nutrition Go mobile application operated by Nutrition Go {"\n"}

                            {"\t"}* Personal Data{"\n"}

                                Personal Data means data about a living individual who can be identified
                                from those data (or from those and other information either in our
                                possession or likely to come into our possession).{"\n"}

                                {"\t"}* Usage Data{"\n"}

                                Usage Data is data collected automatically either generated by the use of
                                the Service or from the Service infrastructure itself (for example, the
                                duration of a page visit).{"\n"}

                                {"\t"}* Cookies{"\n"}

                                Cookies are small files stored on your device (computer or mobile device).{"\n"}{"\n"}

                                {"\t"}Information Collection and Use  {"\n"}
                                {"\t"}------------------------------{"\n"}

                            We collect several different types of information for various purposes to
                            provide and improve our Service to you.{"\n"}{"\n"}

                            {"\t"}Types of Data Collected  {"\n"}
                            {"\t"}~~~~~~~~~~~~~~~~~~~~~~~{"\n"}{"\n"}

                            {"\t"}Personal Data{"\n"}  
                            {"\t"}*************{"\n"}

                            While using our Service, we may ask you to provide us with certain personally
                            identifiable information that can be used to contact or identify you
                            ("Personal Data"). Personally identifiable information may include, but is not
                            limited to:{"\n"}

                            * Email address
                            * First name and last name
                            * Phone number
                            * Cookies and Usage Data{"\n"}{"\n"}

                            {"\t"}Usage Data {"\n"} 
                            {"\t"}**********{"\n"}

                            When you access the Service by or through a mobile device, we may collect
                            certain information automatically, including, but not limited to, the type of
                            mobile device you use, your mobile device unique ID, the IP address of your
                            mobile device, your mobile operating system, the type of mobile Internet
                            browser you use, unique device identifiers and other diagnostic data ("Usage
                            Data").{"\n"}{"\n"}

                            {"\t"}Tracking &amp; Cookies Data  {"\n"}
                            {"\t"}************ {"\n"}

                            We use cookies and similar tracking technologies to track the activity on our
                            Service and we hold certain information.{"\n"}{"\n"}

                            Cookies are files with a small amount of data which may include an anonymous
                            unique identifier. Cookies are sent to your browser from a website and stored
                            on your device. Other tracking technologies are also used such as beacons,
                            tags and scripts to collect and track information and to improve and analyse
                            our Service.{"\n"}{"\n"}

                            You can instruct your browser to refuse all cookies or to indicate when a
                            cookie is being sent. However, if you do not accept cookies, you may not be
                            able to use some portions of our Service.{"\n"}{"\n"}

                            Examples of Cookies we use:{"\n"}

                            * Session Cookies. We use Session Cookies to operate our Service.{"\n"}
                            * Preference Cookies. We use Preference Cookies to remember your preferences
                                and various settings.{"\n"}
                            * Security Cookies. We use Security Cookies for security purposes.{"\n"}{"\n"}

                            {"\t"}Use of Data  {"\n"}
                            {"\t"}-----------{"\n"}

                            Nutrition Go uses the collected data for various purposes:{"\n"}{"\n"}

                            * To provide and maintain the Service{"\n"}
                            * To notify you about changes to our Service{"\n"}
                            * To allow you to participate in interactive features of our Service when
                                you choose to do so{"\n"}
                            * To provide customer care and support{"\n"}
                            * To provide analysis or valuable information so that we can improve the
                                Service{"\n"}
                            * To monitor the usage of the Service{"\n"}
                            * To detect, prevent and address technical issues{"\n"}{"\n"}

                            {"\t"}Transfer Of Data  {"\n"}
                            {"\t"}----------------{"\n"}{"\n"}

                            Your information, including Personal Data, may be transferred to - and
                            maintained on - computers located outside of your state, province, country or
                            other governmental jurisdiction where the data protection laws may differ than
                            those from your jurisdiction.{"\n"}{"\n"}

                            If you are located outside United States and choose to provide information to
                            us, please note that we transfer the data, including Personal Data, to United
                            States and process it there.{"\n"}{"\n"}

                            Your consent to this Privacy Policy followed by your submission of such
                            information represents your agreement to that transfer.{"\n"}{"\n"}

                            Nutrition Go will take all steps reasonably necessary to ensure that your data
                            is treated securely and in accordance with this Privacy Policy and no transfer
                            of your Personal Data will take place to an organization or a country unless
                            there are adequate controls in place including the security of your data and
                            other personal information.{"\n"}{"\n"}

                            {"\t"}Disclosure Of Data  {"\n"}
                            {"\t"}------------------{"\n"}{"\n"}

                            {"\t"}Legal Requirements  {"\n"}
                            {"\t"}~~~~~~~~~~~~~~~~~~{"\n"}{"\n"}

                            Nutrition Go may disclose your Personal Data in the good faith belief that
                            such action is necessary to:{"\n"}

                            * To comply with a legal obligation{"\n"}
                            * To protect and defend the rights or property of Nutrition Go{"\n"}
                            * To prevent or investigate possible wrongdoing in connection with the
                                Service{"\n"}
                            * To protect the personal safety of users of the Service or the public{"\n"}
                            * To protect against legal liability{"\n"}{"\n"}

                            As an European citizen, under GDPR, you have certain individual rights. You
                            can learn more about these guides in the [GDPR
                            Guide](https://termsfeed.com/blog/gdpr/#Individual_Rights_Under_the_GDPR).{"\n"}{"\n"}

                            {"\t"}Security of Data{"\n"}  
                            {"\t"}----------------{"\n"}

                            The security of your data is important to us but remember that no method of
                            transmission over the Internet or method of electronic storage is 100% secure.
                            While we strive to use commercially acceptable means to protect your Personal
                            Data, we cannot guarantee its absolute security.{"\n"}{"\n"}

                            {"\t"}Service Providers  {"\n"}
                            {"\t"}-----------------{"\n"}

                            We may employ third party companies and individuals to facilitate our Service
                            ("Service Providers"), to provide the Service on our behalf, to perform
                            Service-related services or to assist us in analyzing how our Service is used.{"\n"}{"\n"}

                            These third parties have access to your Personal Data only to perform these
                            tasks on our behalf and are obligated not to disclose or use it for any other
                            purpose.{"\n"}{"\n"}

                            {"\t"}Links to Other Sites  {"\n"}
                            {"\t"}--------------------{"\n"}

                            Our Service may contain links to other sites that are not operated by us. If
                            you click a third party link, you will be directed to that third party's site.
                            We strongly advise you to review the Privacy Policy of every site you visit.{"\n"}{"\n"}

                            We have no control over and assume no responsibility for the content, privacy
                            policies or practices of any third party sites or services.{"\n"}{"\n"}

                            {"\t"}Children's Privacy{"\n"}  
                            {"\t"}------------------{"\n"}

                            Our Service does not address anyone under the age of 18 ("Children").{"\n"}{"\n"}

                            We do not knowingly collect personally identifiable information from anyone
                            under the age of 18. If you are a parent or guardian and you are aware that
                            your Child has provided us with Personal Data, please contact us. If we become
                            aware that we have collected Personal Data from children without verification
                            of parental consent, we take steps to remove that information from our
                            servers.{"\n"}{"\n"}

                            {"\t"}Changes to This Privacy Policy  {"\n"}
                            {"\t"}------------------------------{"\n"}

                            We may update our Privacy Policy from time to time. We will notify you of any
                            changes by posting the new Privacy Policy on this page.{"\n"}{"\n"}

                            We will let you know via email and/or a prominent notice on our Service, prior
                            to the change becoming effective and update the "effective date" at the top of
                            this Privacy Policy.{"\n"}{"\n"}

                            You are advised to review this Privacy Policy periodically for any changes.
                            Changes to this Privacy Policy are effective when they are posted on this
                            page.{"\n"}{"\n"}{"\n"}

                            {"\t"}Contact Us {"\n"} 
                            {"\t"}----------{"\n"}

                            If you have any questions about this Privacy Policy, please contact us:{"\n"}{"\n"}

                            * By email: 123@123.com{"\n"}
                            * By phone number: 1234567890{"\n"}


                        </Text>

                        
                        
                    </View>

                    <View style={{ padding: 15, marginTop: 10 }} >

                        <View style= {{alignItems: 'center'}}>

                                <TouchableHighlight
                                    style={styles.buttonStyle}
                                    onPress={() => {
                                        this.go_back();
                                    }}
                                >

                                        <Text style={{ fontWeight: 'bold'}}> Back </Text>

                                </TouchableHighlight>

                        </View>

                    </View>

                </ScrollView>

            </View>
        );

    }

}



const styles = StyleSheet.create({

    buttonStyle: {
        height: 40,
        width: 150,
        borderRadius: 3,
        alignItems: 'center',
        backgroundColor: '#ffff66',
        padding: 10
    },

});

export default PrivacyPolicy;